[package]
name = "process-compose-openapi-client"
version = "1.27.0"
edition = "2021"

[dependencies]
futures = "0.3"
progenitor = { git = "https://github.com/oxidecomputer/progenitor", tag = "v0.8.0", version = "0.8.0"}
reqwest = { version = "^0.12", default-features = false, features = ["json", "stream"] }
serde = { version = "^1.0.42", default-features = false, features = ["derive"] }
serde_json ={ version = "^1.0.42", default-features = false}


[dev-dependencies]
tokio = { version = "1.4", features = ["macros"]}

[build-dependencies]
progenitor = { git = "https://github.com/oxidecomputer/progenitor", tag = "v0.8.0", version = "0.8.0"}
syn = {version = "*"}
prettyplease = {version = "*"}
serde_json ={ version = "^1.0.42", default-features = false}
